
# rustfmt.toml for to-be.Rust
#
# configured for cargo-fmt 1.89.0

array_width=0 # deprecated
# # attr_fn_like_width=70 # deprecated
binop_separator="Front" # default
blank_lines_lower_bound=0
blank_lines_upper_bound=3
brace_style="SameLineWhere" # default
# chain_width=60 # default
color="Auto" # default
combine_control_expr=false
comment_width=100
condense_wildcard_suffixes=false # default
control_brace_style="AlwaysSameLine" # default
disable_all_formatting=false # default
doc_comment_code_block_width=100 # default
edition="2024"
empty_item_single_line=false
enum_discrim_align_threshold=0 # default
error_on_line_overflow=false # default
error_on_unformatted=false # default
# fn_args_layout="Tall" # deprecated
# fn_call_width=60 # deprecated
fn_params_layout="Vertical"
fn_single_line=false # default
force_explicit_abi=true # default
force_multiline_blocks=false # default
# force_code_in_doc_comments=false # deprecated
format_generated_files=true # default
format_macro_bodies=true # default
format_macro_matchers=true
format_strings=false # default
generated_marker_line_search_limit=5 # default
group_imports="Preserve" # default
hard_tabs=false # default
# hide_parse_errors=false # deprecated
hex_literal_case="Preserve" # default
ignore=[
]
imports_granularity="Crate"
imports_indent="Block" # default
imports_layout="Vertical"
indent_style="Block" # default
inline_attribute_width=0 # default
# # license_template_path=""
match_arm_blocks=true # default
match_arm_leading_pipes="Preserve"
match_block_trailing_comma=true
max_width=120
merge_derives=false
# merge_imports= # deprecated
newline_style="Auto" # default
normalize_comments=false # default
normalize_doc_attributes=false # default
overflow_delimited_expr=false # default
remove_nested_parens=true # default
reorder_impl_items=false # default
reorder_imports=true # default
reorder_modules=true # default
# # report_fixme="Always"
# # report_todo="Never"
# required_version="????" # default
single_line_if_else_max_width=50 # default
single_line_let_else_max_width=50 # default
short_array_element_width_threshold=10
show_parse_errors=true # default
skip_children=false # default
skip_macro_invocations=[
]
space_after_colon=true
space_before_colon=true
spaces_around_ranges=false # default
struct_field_align_threshold=20
struct_lit_single_line=false
struct_lit_width=0
struct_variant_width=0
style_edition="2021"
tab_spaces=4 # default
trailing_comma="Vertical" # default
trailing_semicolon=true # default
type_punctuation_density="Wide" # default
unstable_features=false # default
use_field_init_shorthand=true
use_small_heuristics="Default" # default
use_try_shorthand=true # default
# version= # deprecated
where_single_line=false # default
wrap_comments=false # default
